changelog:
  exclude:
    labels:
      - "ignore for release"
  categories:
    - title: ":boom: Breaking Changes"
      labels:
        - "breaking"
    - title: ":rocket: Features"
      labels:
        - "enhancement"
    - title: ":fire: Removals and Deprecations"
      labels:
        - "removal"
    - title: ":beetle: Fixes"
      labels:
        - "bug"
    - title: ":racehorse: Performance"
      labels:
        - "performance"
    - title: ":rotating_light: Testing"
      labels:
        - "testing"
    - title: ":construction_worker: Continuous Integration"
      labels:
        - "ci"
    - title: ":books: Documentation"
      labels:
        - "documentation"
    - title: ":hammer: Refactoring"
      labels:
        - "refactoring"
    - title: ":lipstick: Style"
      labels:
        - "style"
    - title: ":package: Dependencies"
      labels:
        - "dependencies"
        - "build"
    - title: Other Changes
      labels:
        - "*"
